// lib/demoProducts.js
export const demoProducts = [
  {
    id: "1",
    title: "Wireless Bluetooth Earbuds with Charging Case",
    image:
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&auto=format&fit=crop",
    priceMin: 2.5,
    priceMax: 5.0,
    moq: 100,
    supplier: {
      name: "Shenzhen Tech Co., Ltd.",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 8,
      responseRate: 95,
      tradeAssurance: true,
      verified: true,
      logo: "https://via.placeholder.com/100x100?text=Logo", // placeholder
    },
    slug: "wireless-earbuds",
    category: "Electronics",
    rating: 4.5,
    reviews: 128,
    inStock: true,

    description:
      "Experience true wireless freedom with these Bluetooth 5.0 earbuds. Comes with a compact charging case that provides up to 20 hours of playtime. IPX5 water resistant, ergonomic design, and crystal clear sound.",
    specifications: [
      { name: "Bluetooth Version", value: "5.0" },
      { name: "Battery Life", value: "5 hours (earbuds) + 15 hours (case)" },
      { name: "Charging Time", value: "1.5 hours" },
      { name: "Water Resistance", value: "IPX5" },
      { name: "Driver Size", value: "10mm" },
      { name: "Impedance", value: "32Ω" },
    ],
    companyProfile:
      "Shenzhen Tech Co., Ltd. is a leading manufacturer of consumer electronics with over 8 years of experience. We specialize in Bluetooth audio products and have a dedicated R&D team of 20 engineers. Our factory is ISO 9001 certified and we export to over 30 countries.",
    reviews: [
      {
        id: 101,
        user: "John D.",
        rating: 5,
        date: "2024-02-15",
        text: "Great quality for the price. Battery lasts long and sound is clear.",
      },
      {
        id: 102,
        user: "Maria S.",
        rating: 4,
        date: "2024-02-10",
        text: "Good earbuds, comfortable fit. Pairing is easy.",
      },
    ],
    // ...existing code...
  },
  {
    id: "2",
    title: "Men's Casual Slim Fit T-Shirt (100% Cotton)",
    image:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&auto=format&fit=crop",
    priceMin: 3.2,
    priceMax: 6.8,
    moq: 200,
    supplier: {
      name: "Guangzhou Fashion Ltd.",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 5,
      responseRate: 98,
      tradeAssurance: false,
      verified: true,
    },
    slug: "casual-t-shirt",
    category: "Fashion",
    rating: 4.2,
    reviews: 85,
    inStock: true,
  },
  {
    id: "3",
    title: "Stainless Steel Water Bottle 500ml Insulated",
    image:
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&auto=format&fit=crop",
    priceMin: 4.0,
    priceMax: 7.5,
    moq: 150,
    supplier: {
      name: "Yiwu Houseware Co.",
      location: "Zhejiang, China",
      flag: "🇨🇳",
      yearsInBusiness: 10,
      responseRate: 92,
      tradeAssurance: true,
      verified: true,
    },
    slug: "water-bottle",
    category: "Home & Garden",
    rating: 4.7,
    reviews: 203,
    inStock: true,
  },
  {
    id: "4",
    title: "Smart LED TV 32-inch HD Ready",
    image:
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&auto=format&fit=crop",
    priceMin: 120.0,
    priceMax: 145.0,
    moq: 10,
    supplier: {
      name: "Shenzhen Electronics Ltd.",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 12,
      responseRate: 96,
      tradeAssurance: true,
      verified: true,
    },
    slug: "smart-led-tv",
    category: "Electronics",
    rating: 4.3,
    reviews: 56,
    inStock: true,
  },
  {
    id: "5",
    title: "Portable Power Bank 20000mAh",
    image:
      "https://images.unsplash.com/photo-1609592424824-5ba6c7a3d34e?w=400&auto=format&fit=crop",
    priceMin: 8.5,
    priceMax: 12.0,
    moq: 100,
    supplier: {
      name: "Shenzhen Power Ltd.",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 6,
      responseRate: 94,
      tradeAssurance: false,
      verified: true,
    },
    slug: "power-bank",
    category: "Electronics",
    rating: 4.4,
    reviews: 312,
    inStock: true,
  },
  {
    id: "6",
    title: "Women's Yoga Pants High Waist",
    image:
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400&auto=format&fit=crop",
    priceMin: 5.5,
    priceMax: 9.9,
    moq: 150,
    supplier: {
      name: "Ningbo Sportswear",
      location: "Zhejiang, China",
      flag: "🇨🇳",
      yearsInBusiness: 4,
      responseRate: 97,
      tradeAssurance: false,
      verified: true,
    },
    slug: "yoga-pants",
    category: "Fashion",
    rating: 4.1,
    reviews: 47,
    inStock: true,
  },
  {
    id: "7",
    title: "Ceramic Coffee Mug 350ml Set of 6",
    image:
      "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&auto=format&fit=crop",
    priceMin: 2.8,
    priceMax: 4.5,
    moq: 200,
    supplier: {
      name: "Chaozhou Ceramics",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 15,
      responseRate: 91,
      tradeAssurance: true,
      verified: true,
    },
    slug: "coffee-mugs",
    category: "Home & Garden",
    rating: 4.8,
    reviews: 422,
    inStock: true,
  },
  {
    id: "8",
    title: "Fitness Tracker Smart Watch",
    image:
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&auto=format&fit=crop",
    priceMin: 12.0,
    priceMax: 18.5,
    moq: 50,
    supplier: {
      name: "Shenzhen Wearable Tech",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 7,
      responseRate: 93,
      tradeAssurance: true,
      verified: true,
    },
    slug: "fitness-tracker",
    category: "Electronics",
    rating: 4.2,
    reviews: 189,
    inStock: true,
  },
  {
    id: "9",
    title: "Foldable Reusable Shopping Bags (Pack of 5)",
    image:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&auto=format&fit=crop",
    priceMin: 1.2,
    priceMax: 2.5,
    moq: 500,
    supplier: {
      name: "Xiamen Eco Products",
      location: "Fujian, China",
      flag: "🇨🇳",
      yearsInBusiness: 3,
      responseRate: 99,
      tradeAssurance: false,
      verified: false,
    },
    slug: "shopping-bags",
    category: "Home & Garden",
    rating: 4.0,
    reviews: 34,
    inStock: true,
  },
  {
    id: "10",
    title: "Wireless Mechanical Keyboard RGB",
    image:
      "https://images.unsplash.com/photo-1595225476474-87563907a212?w=400&auto=format&fit=crop",
    priceMin: 25.0,
    priceMax: 35.0,
    moq: 20,
    supplier: {
      name: "Shenzhen Peripherals",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 5,
      responseRate: 90,
      tradeAssurance: true,
      verified: true,
    },
    slug: "mechanical-keyboard",
    category: "Electronics",
    rating: 4.6,
    reviews: 274,
    inStock: true,
  },
  {
    id: "11",
    title: "LED Desk Lamp with Wireless Charger",
    image:
      "https://images.unsplash.com/photo-1534073828943-f801091bb18c?w=400&auto=format&fit=crop",
    priceMin: 15.0,
    priceMax: 22.0,
    moq: 30,
    supplier: {
      name: "Ningbo Lighting",
      location: "Zhejiang, China",
      flag: "🇨🇳",
      yearsInBusiness: 8,
      responseRate: 96,
      tradeAssurance: true,
      verified: true,
    },
    slug: "desk-lamp",
    category: "Home & Garden",
    rating: 4.3,
    reviews: 156,
    inStock: true,
  },
  {
    id: "12",
    title: "Digital Kitchen Scale 5kg/1g",
    image:
      "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?w=400&auto=format&fit=crop",
    priceMin: 3.5,
    priceMax: 6.0,
    moq: 100,
    supplier: {
      name: "Yongkang Hardware",
      location: "Zhejiang, China",
      flag: "🇨🇳",
      yearsInBusiness: 9,
      responseRate: 92,
      tradeAssurance: false,
      verified: true,
    },
    slug: "kitchen-scale",
    category: "Home & Garden",
    rating: 4.2,
    reviews: 98,
    inStock: true,
  },
  {
    id: "13",
    title: "Men's Leather Wallet RFID Blocking",
    image:
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&auto=format&fit=crop",
    priceMin: 4.0,
    priceMax: 7.5,
    moq: 100,
    supplier: {
      name: "Guangzhou Leather Goods",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 6,
      responseRate: 95,
      tradeAssurance: false,
      verified: true,
    },
    slug: "leather-wallet",
    category: "Fashion",
    rating: 4.4,
    reviews: 143,
    inStock: true,
  },
  {
    id: "14",
    title: "Portable Bluetooth Speaker Waterproof",
    image:
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&auto=format&fit=crop",
    priceMin: 10.0,
    priceMax: 16.0,
    moq: 50,
    supplier: {
      name: "Shenzhen Audio",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 7,
      responseRate: 94,
      tradeAssurance: true,
      verified: true,
    },
    slug: "bluetooth-speaker",
    category: "Electronics",
    rating: 4.5,
    reviews: 201,
    inStock: true,
  },
  {
    id: "15",
    title: "Rechargeable Headlamp LED 1000 Lumens",
    image:
      "https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=400&auto=format&fit=crop",
    priceMin: 6.5,
    priceMax: 11.0,
    moq: 80,
    supplier: {
      name: "Ningbo Outdoor Gear",
      location: "Zhejiang, China",
      flag: "🇨🇳",
      yearsInBusiness: 5,
      responseRate: 91,
      tradeAssurance: false,
      verified: true,
    },
    slug: "headlamp",
    category: "Sports & Outdoors",
    rating: 4.6,
    reviews: 76,
    inStock: true,
  },
  // Additional products for pagination
  {
    id: "16",
    title: "Electric Kettle Stainless Steel 1.7L",
    image:
      "https://images.unsplash.com/photo-1579722820308-d74e571900e9?w=400&auto=format&fit=crop",
    priceMin: 8.0,
    priceMax: 12.5,
    moq: 60,
    supplier: {
      name: "Guangdong Appliances",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 11,
      responseRate: 93,
      tradeAssurance: true,
      verified: true,
    },
    slug: "electric-kettle",
    category: "Home & Garden",
    rating: 4.3,
    reviews: 87,
    inStock: true,
  },
  {
    id: "17",
    title: "Yoga Mat Non-Slip Eco-Friendly",
    image:
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&auto=format&fit=crop",
    priceMin: 5.0,
    priceMax: 9.0,
    moq: 100,
    supplier: {
      name: "Shanghai Fitness",
      location: "Shanghai, China",
      flag: "🇨🇳",
      yearsInBusiness: 4,
      responseRate: 96,
      tradeAssurance: false,
      verified: true,
    },
    slug: "yoga-mat",
    category: "Sports & Outdoors",
    rating: 4.7,
    reviews: 112,
    inStock: true,
  },
  {
    id: "18",
    title: "Kids Educational Tablet Toy",
    image:
      "https://images.unsplash.com/photo-1584697964409-d96f48bfe47b?w=400&auto=format&fit=crop",
    priceMin: 14.0,
    priceMax: 19.0,
    moq: 30,
    supplier: {
      name: "Shantou Toys",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 7,
      responseRate: 89,
      tradeAssurance: false,
      verified: true,
    },
    slug: "kids-tablet",
    category: "Toys & Kids",
    rating: 4.1,
    reviews: 44,
    inStock: true,
  },
  {
    id: "19",
    title: "Car Dash Cam 1080p",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=400&auto=format&fit=crop",
    priceMin: 22.0,
    priceMax: 30.0,
    moq: 20,
    supplier: {
      name: "Shenzhen Auto Electronics",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 6,
      responseRate: 92,
      tradeAssurance: true,
      verified: true,
    },
    slug: "dash-cam",
    category: "Automotive",
    rating: 4.4,
    reviews: 67,
    inStock: true,
  },
  {
    id: "20",
    title: "Office Desk Organizer Set",
    image:
      "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&auto=format&fit=crop",
    priceMin: 3.0,
    priceMax: 5.5,
    moq: 200,
    supplier: {
      name: "Ningbo Office Supplies",
      location: "Zhejiang, China",
      flag: "🇨🇳",
      yearsInBusiness: 8,
      responseRate: 95,
      tradeAssurance: false,
      verified: true,
    },
    slug: "desk-organizer",
    category: "Office Supplies",
    rating: 4.2,
    reviews: 53,
    inStock: true,
  },
  {
    id: "21",
    title: "Wireless Charger Fast Charging",
    image:
      "https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=400&auto=format&fit=crop",
    priceMin: 6.0,
    priceMax: 10.0,
    moq: 100,
    supplier: {
      name: "Shenzhen Accessories",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 3,
      responseRate: 97,
      tradeAssurance: false,
      verified: true,
    },
    slug: "wireless-charger",
    category: "Electronics",
    rating: 4.5,
    reviews: 212,
    inStock: true,
  },
  {
    id: "22",
    title: "Men's Running Shoes Breathable",
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&auto=format&fit=crop",
    priceMin: 12.0,
    priceMax: 18.0,
    moq: 50,
    supplier: {
      name: "Fujian Footwear",
      location: "Fujian, China",
      flag: "🇨🇳",
      yearsInBusiness: 9,
      responseRate: 94,
      tradeAssurance: true,
      verified: true,
    },
    slug: "running-shoes",
    category: "Fashion",
    rating: 4.6,
    reviews: 187,
    inStock: true,
  },
  {
    id: "23",
    title: "Ceramic Flower Vase Set of 3",
    image:
      "https://images.unsplash.com/photo-1584583570840-0a3d88497593?w=400&auto=format&fit=crop",
    priceMin: 4.5,
    priceMax: 7.0,
    moq: 120,
    supplier: {
      name: "Jingdezhen Ceramics",
      location: "Jiangxi, China",
      flag: "🇨🇳",
      yearsInBusiness: 20,
      responseRate: 90,
      tradeAssurance: true,
      verified: true,
    },
    slug: "flower-vase",
    category: "Home & Garden",
    rating: 4.8,
    reviews: 65,
    inStock: true,
  },
  {
    id: "24",
    title: "LED Strip Lights RGB 5m",
    image:
      "https://images.unsplash.com/photo-1557044405-9e3d2c1f0c2e?w=400&auto=format&fit=crop",
    priceMin: 3.5,
    priceMax: 6.0,
    moq: 150,
    supplier: {
      name: "Shenzhen Lighting",
      location: "Guangdong, China",
      flag: "🇨🇳",
      yearsInBusiness: 5,
      responseRate: 96,
      tradeAssurance: false,
      verified: true,
    },
    slug: "led-strip",
    category: "Electronics",
    rating: 4.3,
    reviews: 342,
    inStock: true,
  },
  {
    id: "25",
    title: "Adjustable Dumbbells Set 20kg",
    image:
      "https://images.unsplash.com/photo-1586401100295-7a8096fd001a?w=400&auto=format&fit=crop",
    priceMin: 35.0,
    priceMax: 45.0,
    moq: 10,
    supplier: {
      name: "Shanghai Fitness Equipment",
      location: "Shanghai, China",
      flag: "🇨🇳",
      yearsInBusiness: 7,
      responseRate: 93,
      tradeAssurance: true,
      verified: true,
    },
    slug: "dumbbells",
    category: "Sports & Outdoors",
    rating: 4.7,
    reviews: 92,
    inStock: true,
  },
];
