// lib/demoSuppliers.js
export const demoSuppliers = [
  {
    id: "shenzhen-tech",
    name: "Shenzhen Tech Co., Ltd.",
    logo: "https://via.placeholder.com/150x150?text=Tech+Logo",
    coverImage:
      "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200&auto=format&fit=crop",
    description:
      "Leading manufacturer of consumer electronics with 8+ years experience. Specializes in Bluetooth audio products.",
    location: "Guangdong, China",
    flag: "🇨🇳",
    yearsInBusiness: 8,
    responseRate: 95,
    responseTime: "Within 2 hours",
    tradeAssurance: true,
    verified: true,
    premium: true,
    rating: 4.8,
    reviewCount: 234,
    productCount: 128,
    mainCategories: ["Electronics", "Audio", "Wearables"],
    contact: {
      email: "info@shenzhentech.com",
      phone: "+86 755 1234 5678",
    },
  },
  {
    id: "guangzhou-fashion",
    name: "Guangzhou Fashion Ltd.",
    logo: "https://via.placeholder.com/150x150?text=Fashion+Logo",
    coverImage:
      "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1200&auto=format&fit=crop",
    description:
      "Professional apparel manufacturer with 5 years experience. Produces high-quality casual wear and sportswear.",
    location: "Guangdong, China",
    flag: "🇨🇳",
    yearsInBusiness: 5,
    responseRate: 98,
    responseTime: "Within 1 hour",
    tradeAssurance: false,
    verified: true,
    premium: false,
    rating: 4.6,
    reviewCount: 187,
    productCount: 95,
    mainCategories: ["Fashion", "Sportswear"],
    contact: {
      email: "sales@guangzhoufashion.com",
      phone: "+86 20 8765 4321",
    },
  },
  {
    id: "yiwu-houseware",
    name: "Yiwu Houseware Co.",
    logo: "https://via.placeholder.com/150x150?text=Yiwu+Logo",
    coverImage:
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?w=1200&auto=format&fit=crop",
    description:
      "Leading supplier of houseware and kitchen products. 10 years of manufacturing experience.",
    location: "Zhejiang, China",
    flag: "🇨🇳",
    yearsInBusiness: 10,
    responseRate: 92,
    responseTime: "Within 4 hours",
    tradeAssurance: true,
    verified: true,
    premium: true,
    rating: 4.5,
    reviewCount: 156,
    productCount: 210,
    mainCategories: ["Home & Garden", "Kitchen"],
    contact: {
      email: "info@yiwuhouseware.com",
      phone: "+86 579 1234 5678",
    },
  },
  {
    id: "ningbo-sportswear",
    name: "Ningbo Sportswear",
    logo: "https://via.placeholder.com/150x150?text=Ningbo+Logo",
    coverImage:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&auto=format&fit=crop",
    description:
      "Specialized in yoga wear and fitness apparel. 4 years in business.",
    location: "Zhejiang, China",
    flag: "🇨🇳",
    yearsInBusiness: 4,
    responseRate: 97,
    responseTime: "Within 1 hour",
    tradeAssurance: false,
    verified: true,
    premium: false,
    rating: 4.7,
    reviewCount: 98,
    productCount: 67,
    mainCategories: ["Sports", "Fashion"],
    contact: {
      email: "contact@ningbosportswear.com",
      phone: "+86 574 8765 4321",
    },
  },
  {
    id: "chaozhou-ceramics",
    name: "Chaozhou Ceramics",
    logo: "https://via.placeholder.com/150x150?text=Ceramics+Logo",
    coverImage:
      "https://images.unsplash.com/photo-1565182999561-18d7dc61c392?w=1200&auto=format&fit=crop",
    description:
      "Traditional ceramic manufacturer with 15 years of heritage. Specializes in dinnerware and decorative items.",
    location: "Guangdong, China",
    flag: "🇨🇳",
    yearsInBusiness: 15,
    responseRate: 91,
    responseTime: "Within 6 hours",
    tradeAssurance: true,
    verified: true,
    premium: true,
    rating: 4.9,
    reviewCount: 312,
    productCount: 89,
    mainCategories: ["Home & Garden", "Decor"],
    contact: {
      email: "sales@chaozhouceramics.com",
      phone: "+86 768 1234 5678",
    },
  },
  {
    id: "xiamen-eco",
    name: "Xiamen Eco Products",
    logo: "https://via.placeholder.com/150x150?text=Eco+Logo",
    coverImage:
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b29?w=1200&auto=format&fit=crop",
    description:
      "Sustainable and eco-friendly products manufacturer. 3 years in business.",
    location: "Fujian, China",
    flag: "🇨🇳",
    yearsInBusiness: 3,
    responseRate: 99,
    responseTime: "Within 30 minutes",
    tradeAssurance: false,
    verified: false,
    premium: false,
    rating: 4.2,
    reviewCount: 45,
    productCount: 34,
    mainCategories: ["Home & Garden", "Eco-Friendly"],
    contact: {
      email: "info@xiameneco.com",
      phone: "+86 592 8765 4321",
    },
  },
  {
    id: "shenzhen-peripherals",
    name: "Shenzhen Peripherals",
    logo: "https://via.placeholder.com/150x150?text=Peripherals+Logo",
    coverImage:
      "https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=1200&auto=format&fit=crop",
    description:
      "Computer peripherals and accessories manufacturer. 5 years of experience.",
    location: "Guangdong, China",
    flag: "🇨🇳",
    yearsInBusiness: 5,
    responseRate: 90,
    responseTime: "Within 3 hours",
    tradeAssurance: true,
    verified: true,
    premium: false,
    rating: 4.4,
    reviewCount: 123,
    productCount: 76,
    mainCategories: ["Electronics", "Computer Accessories"],
    contact: {
      email: "sales@szperipherals.com",
      phone: "+86 755 2345 6789",
    },
  },
  {
    id: "ningbo-lighting",
    name: "Ningbo Lighting",
    logo: "https://via.placeholder.com/150x150?text=Lighting+Logo",
    coverImage:
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=1200&auto=format&fit=crop",
    description:
      "LED lighting solutions for home and commercial use. 8 years in business.",
    location: "Zhejiang, China",
    flag: "🇨🇳",
    yearsInBusiness: 8,
    responseRate: 96,
    responseTime: "Within 2 hours",
    tradeAssurance: true,
    verified: true,
    premium: true,
    rating: 4.7,
    reviewCount: 201,
    productCount: 112,
    mainCategories: ["Electronics", "Lighting"],
    contact: {
      email: "info@ningbolighting.com",
      phone: "+86 574 3456 7890",
    },
  },
];

export const getSupplierById = (id) => demoSuppliers.find((s) => s.id === id);
