// lib/returnData.js
export const returnReasons = [
  { value: "changed_mind", label: "Changed my mind" },
  { value: "wrong_item", label: "Wrong item received" },
  { value: "damaged", label: "Item damaged" },
  { value: "not_as_described", label: "Item not as described" },
  { value: "quality_issue", label: "Quality issue" },
  { value: "better_price", label: "Found better price elsewhere" },
  { value: "other", label: "Other" },
];

export const returnStatuses = {
  REQUESTED: "Return requested",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  LABEL_GENERATED: "Return label generated",
  SHIPPED: "Item shipped back",
  RECEIVED: "Item received by seller",
  INSPECTED: "Inspected",
  REFUNDED: "Refund processed",
  CLOSED: "Closed",
};

export const resolutionOptions = [
  { value: "refund", label: "Refund to original payment" },
  { value: "credit", label: "Store credit" },
  { value: "exchange_same", label: "Exchange for same item" },
  { value: "exchange_different", label: "Exchange for different item" },
];

// Mock return requests
export const mockReturns = [
  {
    id: "RET-1001",
    orderId: "ORD-12345",
    orderDate: "2025-02-15",
    buyerId: "user1",
    buyerName: "John Smith",
    buyerEmail: "john.smith@example.com",
    sellerId: "seller1",
    sellerName: "Shenzhen Tech Co.",
    productId: "prod1",
    productName: "Wireless Bluetooth Earbuds",
    productImage:
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=100&auto=format",
    quantity: 1,
    price: 29.99,
    reason: "damaged",
    reasonText: "The left earbud doesn't work at all.",
    resolution: "refund",
    status: "Return requested",
    requestDate: "2025-02-22T10:30:00Z",
    sellerResponseDate: null,
    sellerNote: "",
    evidence: ["photo1.jpg"],
    trackingNumber: null,
    carrier: null,
    returnLabel: null,
    refundAmount: null,
    refundDate: null,
    timeline: [
      {
        action: "requested",
        by: "buyer",
        at: "2025-02-22T10:30:00Z",
        note: "Return requested",
      },
    ],
    messages: [],
  },
  {
    id: "RET-1002",
    orderId: "ORD-12346",
    orderDate: "2025-02-10",
    buyerId: "user2",
    buyerName: "Emma Wilson",
    buyerEmail: "emma.w@example.com",
    sellerId: "seller2",
    sellerName: "Guangzhou Fashion Ltd.",
    productId: "prod2",
    productName: "Women's Yoga Pants",
    productImage:
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=100&auto=format",
    quantity: 1,
    price: 29.99,
    reason: "wrong_item",
    reasonText: "Received size M but ordered size S.",
    resolution: "exchange_same",
    status: "Approved",
    requestDate: "2025-02-20T14:15:00Z",
    sellerResponseDate: "2025-02-21T09:00:00Z",
    sellerNote: "We'll send a replacement.",
    evidence: [],
    trackingNumber: "1Z999AA10123456784",
    carrier: "UPS",
    returnLabel: "https://example.com/label.pdf",
    refundAmount: null,
    refundDate: null,
    timeline: [
      {
        action: "requested",
        by: "buyer",
        at: "2025-02-20T14:15:00Z",
        note: "Return requested",
      },
      {
        action: "approved",
        by: "seller",
        at: "2025-02-21T09:00:00Z",
        note: "Return approved, replacement to be sent",
      },
    ],
    messages: [
      {
        id: 1,
        from: "seller",
        text: "Please ship the item back to our warehouse.",
        timestamp: "2025-02-21T09:05:00Z",
      },
    ],
  },
  {
    id: "RET-1003",
    orderId: "ORD-12347",
    orderDate: "2025-02-05",
    buyerId: "user3",
    buyerName: "Michael Brown",
    buyerEmail: "michael.b@example.com",
    sellerId: "seller1",
    sellerName: "Shenzhen Tech Co.",
    productId: "prod3",
    productName: "Smart LED TV",
    productImage:
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=100&auto=format",
    quantity: 1,
    price: 320.0,
    reason: "damaged",
    reasonText: "Screen is cracked.",
    resolution: "refund",
    status: "Item received by seller",
    requestDate: "2025-02-08T09:00:00Z",
    sellerResponseDate: "2025-02-09T11:30:00Z",
    sellerNote: "Approved, please return.",
    evidence: ["cracked.jpg"],
    trackingNumber: "1Z999BB20234567890",
    carrier: "USPS",
    returnLabel: "https://example.com/label2.pdf",
    refundAmount: null,
    refundDate: null,
    timeline: [
      {
        action: "requested",
        by: "buyer",
        at: "2025-02-08T09:00:00Z",
        note: "Return requested",
      },
      {
        action: "approved",
        by: "seller",
        at: "2025-02-09T11:30:00Z",
        note: "Return approved",
      },
      {
        action: "shipped",
        by: "buyer",
        at: "2025-02-10T15:20:00Z",
        note: "Item shipped back",
      },
      {
        action: "received",
        by: "seller",
        at: "2025-02-15T10:00:00Z",
        note: "Item received by seller",
      },
    ],
    messages: [],
  },
  {
    id: "RET-1004",
    orderId: "ORD-12348",
    orderDate: "2025-02-01",
    buyerId: "user4",
    buyerName: "Sarah Davis",
    buyerEmail: "sarah.d@example.com",
    sellerId: "seller3",
    sellerName: "Yiwu Houseware Co.",
    productId: "prod4",
    productName: "Ceramic Coffee Mug Set",
    productImage:
      "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=100&auto=format",
    quantity: 1,
    price: 34.99,
    reason: "changed_mind",
    reasonText: "No longer needed.",
    resolution: "refund",
    status: "Refund processed",
    requestDate: "2025-02-03T16:45:00Z",
    sellerResponseDate: "2025-02-04T10:00:00Z",
    sellerNote: "Approved, refund issued.",
    evidence: [],
    trackingNumber: null,
    carrier: null,
    returnLabel: null,
    refundAmount: 34.99,
    refundDate: "2025-02-05T14:30:00Z",
    timeline: [
      {
        action: "requested",
        by: "buyer",
        at: "2025-02-03T16:45:00Z",
        note: "Return requested",
      },
      {
        action: "approved",
        by: "seller",
        at: "2025-02-04T10:00:00Z",
        note: "Return approved",
      },
      {
        action: "refunded",
        by: "seller",
        at: "2025-02-05T14:30:00Z",
        note: "Refund processed",
      },
    ],
    messages: [],
  },
];
